# Generated by Django 3.0.8 on 2020-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(default='Empresa', max_length=255)),
                ('demanda_contratada', models.CharField(default='000', max_length=255)),
                ('demanda_registrada', models.CharField(default='000', max_length=255)),
                ('consumo_ponta', models.CharField(default='000', max_length=255)),
                ('slug', models.SlugField(blank=True, default='000')),
            ],
        ),
    ]
