# Generated by Django 3.0.8 on 2020-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200812_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='consumo_Fora_ponta',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='consumo_ponta',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='demanda_contratada',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='demanda_registrada',
            field=models.CharField(default='000', max_length=255),
        ),
    ]
