# Generated by Django 3.0.8 on 2020-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200812_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images'),
        ),
    ]
