# Generated by Django 3.0.8 on 2020-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_empresa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='images'),
        ),
    ]
