# Generated by Django 3.0.8 on 2020-08-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200819_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='image',
        ),
    ]
