# Generated by Django 3.0.8 on 2020-08-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_empresa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='consumo_Fora_ponta',
            field=models.DecimalField(decimal_places=2, default='000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='consumo_ponta',
            field=models.DecimalField(decimal_places=2, default='000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='demanda_contratada',
            field=models.DecimalField(decimal_places=2, default='000', max_digits=5),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='demanda_registrada',
            field=models.DecimalField(decimal_places=2, default='000', max_digits=5),
        ),
    ]
